name: story telling

on:
  issues:
    types: [opened]
  issue_comment:
    types:
      - created
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [ created ]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      if: ${{ github.event.issue.pull_request == null }}  # Only run if it's NOT a PR comment
      uses: actions/checkout@v3

    - name: Checkout PR head branch
      if: ${{ github.event.issue.pull_request != null }}  # Only run if it's a PR comment
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}  # Checkout the PR head branch

    - name: Display the current branch
      run: git branch

    - name: Print pull request details
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "github.event.issue.pull_request - ${{ github.event.issue.pull_request }}"
        echo "github.event.pull_request.head.ref - ${{ github.event.pull_request.head.ref }}"
        echo "github.event.issue.pull_request.head.ref - ${{ github.event.issue.pull_request.head.ref }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Print Job details
      run: |  
        echo "Run ID - ${{ github.run_id }}"
        echo "Run No - ${{ github.run_number }}"
        echo "Job    - ${{ github.job }}"
        echo "Job ID - ${{ github.job_id }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install git-bob
      run: |
        pip install git-bob==0.12.0

    - name: Run git-bob
      env:
        GIT_BOB_AGENT_NAME: "story-teller"
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
        GIT_BOB_LLM_NAME: "${{ secrets.GIT_BOB_LLM_NAME }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GH_MODELS_API_KEY: "${{ secrets.GH_MODELS_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_RUN_ID: "${{ github.run_id }}"
        TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
        TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
        SYSTEM_MESSAGE: |
          You are an extremely skilled children story teller. You typically write texts and paint images for 5 year old kids.
          
        VISION_SYSTEM_MESSAGE: |
          You are a childrens art expert and you describe images in a language like 5 year old kids would.
          
      run: |
        git-bob github-action ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.issue.number }}
